export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const UPDATE_NAME_REQUEST = "UPDATE_NAME_REQUEST";
export const UPDATE_NAME_SUCCESS = "UPDATE_NAME_SUCCESS";
export const UPDATE_NAME_FAIL = "UPDATE_NAME_FAIL";
export const UPDATE_NAME_RESET = "UPDATE_NAME_RESET";

export const UPDATE_EMAIL_REQUEST = "UPDATE_EMAIL_REQUEST";
export const UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS";
export const UPDATE_EMAIL_FAIL = "UPDATE_EMAIL_FAIL";
export const UPDATE_EMAIL_RESET = "UPDATE_EMAIL_RESET";

export const UPDATE_COLLEGENAME_REQUEST = "UPDATE_COLLEGENAME_REQUEST";
export const UPDATE_COLLEGENAME_SUCCESS = "UPDATE_COLLEGENAME_SUCCESS";
export const UPDATE_COLLEGENAME_FAIL = "UPDATE_COLLEGENAME_FAIL";
export const UPDATE_COLLEGENAME_RESET = "UPDATE_COLLEGENAME_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";